version: '3.4'

services:
  wikiscroll:
    image: wikiscroll
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
